import 'package:flutter/material.dart';

class LanguageProvider extends ChangeNotifier {
  String _language = "English";

  String get language => _language;

  void setLanguage(String lang) {
    _language = lang;
    notifyListeners();
  }

  String t(String key) {
    return _translations[_language]?[key] ?? key;
  }

  final Map<String, Map<String, String>> _translations = {
    "English": {
      "app_title": "Residence App",
      "app_subtitle": "Smart Residential Management",
      "sign_in": "Sign In",
      "email": "Email",
      "password": "Password",
      "login_button": "Sign In",
      "login_error": "Email or Password is incorrect!",
      "home": "Home",
      "welcome": "Welcome 👋",
      "logout": "Logout",
      "my_profile": "My Profile",
      "my_profile_sub": "View your personal information",
      "maintenance": "Maintenance Request",
      "maintenance_sub": "Send a repair or maintenance request",
      "visitor": "Visitor Access",
      "visitor_sub": "Add a visitor and generate QR Code",
      "vehicle": "Vehicle Registration",
      "vehicle_sub": "Register your vehicle",
      "parking": "Parking",
      "parking_sub": "Check parking spot availability",
      "payments": "Payments",
      "payments_sub": "Pay your bills and view history",
      "community": "Community Feed",
      "community_sub": "News and announcements",
      "messages": "Messages",
      "messages_sub": "Chat with residents and staff",
      "phone": "Phone",
      "building": "Building",
      "floor": "Floor",
      "apartment": "Apartment Number",
      "problem_type": "Problem Type",
      "problem_desc": "Problem Description",
      "send_request": "Send Request",
      "new_request": "New Request",
      "request_sent": "Request Sent Successfully!",
      "contact_soon": "We will contact you soon",
      "visitor_info": "Visitor Information",
      "visitor_name": "Visitor Name",
      "phone_number": "Phone Number",
      "generate_qr": "Generate QR Code",
      "show_qr": "Show this QR Code at the entrance",
      "add_visitor": "Add Another Visitor",
      "vehicle_info": "Vehicle Information",
      "license_plate": "License Plate",
      "car_brand": "Car Brand",
      "car_color": "Car Color",
      "register_vehicle": "Register Vehicle",
      "vehicle_registered": "Vehicle Registered!",
      "register_another": "Register Another Vehicle",
      "available": "Available",
      "occupied": "Occupied",
      "reserved": "Reserved",
      "unpaid_bills": "Unpaid Bills",
      "total_due": "Total Due",
      "paid": "Paid",
      "notifications": "Notifications",
      "mark_all_read": "Mark all read",
      "my_tasks": "My Tasks",
      "start": "Start",
      "complete": "Complete",
      "upload_photo": "Upload Repair Photo",
      "photo_uploaded": "Photo uploaded",
      "security_control": "Security Control",
      "alerts": "🚨 Alerts",
      "visitor_requests": "👥 Visitor Entry Requests",
      "approve": "Approve",
      "reject": "Reject",
      "community_feed": "Community Feed",
      "announcement": "Announcement",
      "select_language": "Select Language",
      "white": "White",
      "black": "Black",
      "red": "Red",
      "blue": "Blue",
      "silver": "Silver",
      "other": "Other",
      "electricity": "Electricity",
      "plumbing": "Plumbing",
      "air_conditioning": "Air Conditioning",
      "door_window": "Door / Window",
    },
    "عربي": {
      "app_title": "تطبيق السكن",
      "app_subtitle": "إدارة سكنية ذكية",
      "sign_in": "تسجيل الدخول",
      "email": "البريد الإلكتروني",
      "password": "كلمة المرور",
      "login_button": "دخول",
      "login_error": "البريد أو كلمة المرور غلط!",
      "home": "الرئيسية",
      "welcome": "مرحبا بك 👋",
      "logout": "خروج",
      "my_profile": "ملفي الشخصي",
      "my_profile_sub": "عرض معلوماتك الشخصية",
      "maintenance": "طلب صيانة",
      "maintenance_sub": "إرسال طلب إصلاح أو صيانة",
      "visitor": "دخول الزوار",
      "visitor_sub": "إضافة زائر وإنشاء رمز QR",
      "vehicle": "تسجيل السيارة",
      "vehicle_sub": "تسجيل سيارتك",
      "parking": "الباركينغ",
      "parking_sub": "التحقق من توفر أماكن الوقوف",
      "payments": "المدفوعات",
      "payments_sub": "دفع الفواتير وعرض السجل",
      "community": "مجتمع السكان",
      "community_sub": "الأخبار والإعلانات",
      "messages": "الرسائل",
      "messages_sub": "التحدث مع السكان والموظفين",
      "phone": "الهاتف",
      "building": "العمارة",
      "floor": "الطابق",
      "apartment": "رقم الشقة",
      "problem_type": "نوع المشكلة",
      "problem_desc": "وصف المشكلة",
      "send_request": "إرسال الطلب",
      "new_request": "طلب جديد",
      "request_sent": "تم إرسال الطلب بنجاح!",
      "contact_soon": "سيتم التواصل معك قريباً",
      "visitor_info": "معلومات الزائر",
      "visitor_name": "اسم الزائر",
      "phone_number": "رقم الهاتف",
      "generate_qr": "إنشاء رمز QR",
      "show_qr": "أظهر هذا الرمز عند المدخل",
      "add_visitor": "إضافة زائر آخر",
      "vehicle_info": "معلومات السيارة",
      "license_plate": "رقم اللوحة",
      "car_brand": "ماركة السيارة",
      "car_color": "لون السيارة",
      "register_vehicle": "تسجيل السيارة",
      "vehicle_registered": "تم تسجيل السيارة!",
      "register_another": "تسجيل سيارة أخرى",
      "available": "متاح",
      "occupied": "مشغول",
      "reserved": "محجوز",
      "unpaid_bills": "الفواتير غير المدفوعة",
      "total_due": "المبلغ الكلي",
      "paid": "مدفوع",
      "notifications": "الإشعارات",
      "mark_all_read": "تعليم الكل كمقروء",
      "my_tasks": "مهامي",
      "start": "ابدأ",
      "complete": "إنهاء",
      "upload_photo": "رفع صورة الإصلاح",
      "photo_uploaded": "تم رفع الصورة",
      "security_control": "مراقبة الأمن",
      "alerts": "🚨 التنبيهات",
      "visitor_requests": "👥 طلبات دخول الزوار",
      "approve": "موافقة",
      "reject": "رفض",
      "community_feed": "مجتمع السكان",
      "announcement": "إعلان",
      "select_language": "اختر اللغة",
      "white": "أبيض",
      "black": "أسود",
      "red": "أحمر",
      "blue": "أزرق",
      "silver": "فضي",
      "other": "أخرى",
      "electricity": "كهرباء",
      "plumbing": "سباكة",
      "air_conditioning": "تكييف",
      "door_window": "باب / نافذة",
    },
    "Français": {
      "app_title": "Residence App",
      "app_subtitle": "Gestion Résidentielle Intelligente",
      "sign_in": "Connexion",
      "email": "Email",
      "password": "Mot de passe",
      "login_button": "Se connecter",
      "login_error": "Email ou mot de passe incorrect!",
      "home": "Accueil",
      "welcome": "Bienvenue 👋",
      "logout": "Déconnexion",
      "my_profile": "Mon Profil",
      "my_profile_sub": "Voir vos informations personnelles",
      "maintenance": "Demande de maintenance",
      "maintenance_sub": "Envoyer une demande de réparation",
      "visitor": "Accès visiteur",
      "visitor_sub": "Ajouter un visiteur et générer un QR Code",
      "vehicle": "Enregistrement du véhicule",
      "vehicle_sub": "Enregistrer votre véhicule",
      "parking": "Parking",
      "parking_sub": "Vérifier la disponibilité des places",
      "payments": "Paiements",
      "payments_sub": "Payer vos factures",
      "community": "Communauté",
      "community_sub": "Actualités et annonces",
      "messages": "Messages",
      "messages_sub": "Discuter avec les résidents",
      "phone": "Téléphone",
      "building": "Bâtiment",
      "floor": "Étage",
      "apartment": "Numéro d'appartement",
      "problem_type": "Type de problème",
      "problem_desc": "Description du problème",
      "send_request": "Envoyer la demande",
      "new_request": "Nouvelle demande",
      "request_sent": "Demande envoyée avec succès!",
      "contact_soon": "Nous vous contacterons bientôt",
      "visitor_info": "Informations du visiteur",
      "visitor_name": "Nom du visiteur",
      "phone_number": "Numéro de téléphone",
      "generate_qr": "Générer le QR Code",
      "show_qr": "Montrez ce QR Code à l'entrée",
      "add_visitor": "Ajouter un autre visiteur",
      "vehicle_info": "Informations du véhicule",
      "license_plate": "Plaque d'immatriculation",
      "car_brand": "Marque du véhicule",
      "car_color": "Couleur du véhicule",
      "register_vehicle": "Enregistrer le véhicule",
      "vehicle_registered": "Véhicule enregistré!",
      "register_another": "Enregistrer un autre véhicule",
      "available": "Disponible",
      "occupied": "Occupé",
      "reserved": "Réservé",
      "unpaid_bills": "Factures impayées",
      "total_due": "Total dû",
      "paid": "Payé",
      "notifications": "Notifications",
      "mark_all_read": "Tout marquer comme lu",
      "my_tasks": "Mes tâches",
      "start": "Commencer",
      "complete": "Terminer",
      "upload_photo": "Télécharger photo de réparation",
      "photo_uploaded": "Photo téléchargée",
      "security_control": "Contrôle de sécurité",
      "alerts": "🚨 Alertes",
      "visitor_requests": "👥 Demandes d'entrée des visiteurs",
      "approve": "Approuver",
      "reject": "Rejeter",
      "community_feed": "Communauté",
      "announcement": "Annonce",
      "select_language": "Choisir la langue",
      "white": "Blanc",
      "black": "Noir",
      "red": "Rouge",
      "blue": "Bleu",
      "silver": "Argenté",
      "other": "Autre",
      "electricity": "Électricité",
      "plumbing": "Plomberie",
      "air_conditioning": "Climatisation",
      "door_window": "Porte / Fenêtre",
    },
  };
}